# Create a new release

name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ci-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    name: Release
    needs: call-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          name: vscode_krunner
          path: artifacts

      - name: Rename artifact with version
        run: |
          VERSION=${GITHUB_REF_NAME}
          mv artifacts/vscode_krunner-*.tar.gz artifacts/vscode_krunner-${VERSION}.tar.gz

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: artifacts/vscode_krunner-*.tar.gz
